# Generated by Django 5.2.13 on 2026-04-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("odometer_km", models.PositiveIntegerField()),
                ("liters", models.DecimalField(decimal_places=3, max_digits=7)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_liter", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasolina"),
                            ("ethanol", "Etanol"),
                            ("premium_gasoline", "Gasolina Aditivada"),
                        ],
                        default="gasoline",
                        max_length=32,
                    ),
                ),
                ("station_name", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fuel_records", to="garage.motorcycle"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-odometer_km"],
            },
        ),
    ]
