# Generated by Django 5.2.13 on 2026-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrecord",
            name="tank_full",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fuelrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fuelrecord",
            name="odometer_km",
            field=models.PositiveIntegerField(help_text="Odômetro da moto no momento do abastecimento"),
        ),
    ]
