# Generated by Django 5.2.13 on 2026-04-17 10:38

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_fuelgrade_default_price_per_liter_currency_and_more'),
        ('garage', '0007_motorcycle_riding_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('premium_gasoline', 'Gasolina Aditivada'), ('premium_ethanol', 'Etanol Premium')], default='gasoline', max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=120)),
                ('price_per_liter_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3, null=True)),
                ('price_per_liter', djmoney.models.fields.MoneyField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tank_full', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_preferences', to='fuel.fuelgrade')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_preferences', to='garage.motorcycle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_preferences', to='fuel.fuelstation')),
            ],
            options={
                'ordering': ['-last_used_at', '-use_count', '-updated_at'],
            },
        ),
    ]
