# Generated by Django 5.2.13 on 2026-04-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_fuelpreference'),
        ('garage', '0008_alter_motorcycle_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelgrade',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelpreference',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['date'], name='fuel_record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['motorcycle', 'date'], name='fuel_record_moto_date_idx'),
        ),
    ]
