# Generated by Django 5.2.13 on 2026-04-20 15:20

import django.db.models.deletion
from django.db import migrations, models

import apps.fuel.models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_alter_fuelgrade_owner_alter_fuelpreference_owner_and_more'),
        ('garage', '0008_alter_motorcycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to='fuel/receipts/%Y/%m/', validators=[apps.fuel.models.validate_receipt_file]),
        ),
        migrations.CreateModel(
            name='FuelReviewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fillups_interval', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_review_preference', to='garage.motorcycle')),
            ],
            options={
                'verbose_name': 'Regra de revisão por abastecimento',
                'verbose_name_plural': 'Regras de revisão por abastecimento',
            },
        ),
    ]
