# Generated by Django 5.2.13 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_fuelrecord_receipt_file_fuelreviewpreference'),
        ('garage', '0008_alter_motorcycle_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['motorcycle', 'date', 'odometer_km'], name='fuel_moto_date_odo_idx'),
        ),
    ]
