# Generated by Django 5.2.13 on 2026-04-23 04:31

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max, Sum

PREFERENCE_KEY = ("owner_id", "motorcycle_id", "station_id", "fuel_grade_id", "fuel_type", "station_name")


def dedupe_fuel_preferences(apps, schema_editor):
    FuelPreference = apps.get_model("fuel", "FuelPreference")
    duplicates = (
        FuelPreference.objects.values(*PREFERENCE_KEY)
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )

    for duplicate in duplicates:
        lookup = {field: duplicate[field] for field in PREFERENCE_KEY}
        rows = FuelPreference.objects.filter(**lookup).order_by("-last_used_at", "-updated_at", "-id")
        keeper = rows.first()
        if keeper is None:
            continue
        totals = rows.aggregate(use_count_total=Sum("use_count"), latest_used_at=Max("last_used_at"))
        keeper.use_count = totals["use_count_total"] or 0
        keeper.last_used_at = totals["latest_used_at"]
        keeper.save(update_fields=["use_count", "last_used_at", "updated_at"])
        rows.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0008_fuelrecord_fuel_moto_date_odo_idx"),
        ("garage", "0010_motorcyclespec_consumption_avg_km_l_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_fuel_preferences, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fuelpreference",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.comparison.Coalesce("motorcycle_id", models.Value(0)),
                django.db.models.functions.comparison.Coalesce("station_id", models.Value(0)),
                django.db.models.functions.comparison.Coalesce("fuel_grade_id", models.Value(0)),
                models.F("fuel_type"),
                models.F("station_name"),
                name="fuel_preference_unique_pattern",
            ),
        ),
    ]
