name: moto_track

x-db: &db_common
  image: postgres:16
  env_file:
    - .env
  environment:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  healthcheck:
    test:
      [
        "CMD-SHELL",
        "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB",
      ]
    interval: 5s
    timeout: 3s
    retries: 20
    start_period: 10s
  restart: unless-stopped
  volumes:
    - postgres_data:/var/lib/postgresql/data

x-web: &web_common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    DATABASE_URL: ${DATABASE_URL_DOCKER}
  depends_on:
    db:
      condition: service_healthy
  restart: unless-stopped
  user: "1000:1000"

services:
  db:
    <<: *db_common

  web:
    <<: *web_common
    command: python manage.py runserver 0.0.0.0:8000
    profiles: ["dev"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "1"

  web-prod:
    <<: *web_common
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 4 --timeout 60"
    profiles: ["prod"]
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY_PROD}
      DJANGO_SETTINGS_MODULE: config.settings.prod
      DJANGO_DEBUG: "0"

volumes:
  postgres_data:
