[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts =
    --reuse-db
    -ra
    --strict-markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    security: marks tests as security related
    performance: marks tests as performance related
    regression: marks tests as regression related
    e2e: marks tests as end-to-end / browser tests
    lighthouse: marks tests as Lighthouse performance tests
    smoke: marks tests as smoke tests
