# Generated by Django 5.2.13 on 2026-04-13 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(blank=True, max_length=16)),
                ('odometer_current', models.PositiveIntegerField(default=0)),
                ('fuel_tank_capacity_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_tire_pressure_front', models.CharField(blank=True, max_length=32)),
                ('recommended_tire_pressure_rear', models.CharField(blank=True, max_length=32)),
                ('oil_spec_recommendation', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
