# Generated by Django 5.2.13 on 2026-04-15 11:05

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0004_motorcycle_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="observations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="previous_owners",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="purchase_price",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="purchase_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Brazilian Real")], default="BRL", editable=False, max_length=3, null=True
            ),
        ),
    ]
