# Generated by Django 5.2.13 on 2026-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0005_motorcycle_observations_motorcycle_previous_owners_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="current_odometer_km",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="current_odometer_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
