# Generated by Django 5.2.13 on 2026-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_motorcycle_current_odometer_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='riding_profile',
            field=models.CharField(choices=[('auto', 'Automático'), ('urban', 'Urbano'), ('mixed', 'Misto'), ('highway', 'Estrada'), ('severe', 'Uso severo')], default='auto', max_length=16),
        ),
    ]
