# Generated by Django 5.2.13 on 2026-04-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_motorcycle_riding_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL),
        ),
    ]
