# Generated by Django 5.2.13 on 2026-04-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('engine_cc', models.PositiveIntegerField()),
                ('country_code', models.CharField(default='BR', max_length=2)),
            ],
            options={
                'ordering': ['brand', 'model', 'year_from', 'variant'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'model', 'year_from', 'year_to', 'variant', 'country_code'), name='garage_tpl_brand_model_year_variant_country_uniq')],
            },
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_motorcycles', to='garage.motorcycletemplate'),
        ),
        migrations.CreateModel(
            name='MotorcycleTemplateSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_tank_capacity_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuel_type_recommendation', models.CharField(blank=True, max_length=80)),
                ('fuel_octane_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oil_capacity_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tire_size_front', models.CharField(blank=True, max_length=32)),
                ('tire_size_rear', models.CharField(blank=True, max_length=32)),
                ('tire_speed_rating', models.CharField(blank=True, max_length=8)),
                ('battery_spec', models.CharField(blank=True, max_length=80)),
                ('chain_size', models.CharField(blank=True, max_length=32)),
                ('recommended_tire_pressure_front', models.CharField(blank=True, max_length=32)),
                ('recommended_tire_pressure_rear', models.CharField(blank=True, max_length=32)),
                ('oil_type_recommendation', models.CharField(blank=True, max_length=80)),
                ('oil_viscosity_recommendation', models.CharField(blank=True, max_length=32)),
                ('manual_url', models.CharField(blank=True, max_length=500)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='garage.motorcycletemplate')),
            ],
            options={
                'verbose_name': 'Especificacao do template',
                'verbose_name_plural': 'Especificacoes dos templates',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleTemplateMaintenanceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Troca de oleo'), ('oil_filter', 'Filtro de oleo'), ('air_filter', 'Filtro de ar'), ('chain_set', 'Relacao'), ('brake_pad', 'Pastilha de freio'), ('spark_plug', 'Vela'), ('battery', 'Bateria'), ('review', 'Revisao'), ('labor', 'Mao de obra'), ('other', 'Outro')], max_length=32)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_severe_duty_override', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_intervals', to='garage.motorcycletemplate')),
            ],
            options={
                'ordering': ['maintenance_type', 'is_severe_duty_override', 'id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'maintenance_type', 'is_severe_duty_override'), name='garage_tpl_interval_unique_by_type_and_severe')],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleTemplateRecommendedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Troca de oleo'), ('oil_filter', 'Filtro de oleo'), ('air_filter', 'Filtro de ar'), ('chain_set', 'Relacao'), ('brake_pad', 'Pastilha de freio'), ('spark_plug', 'Vela'), ('battery', 'Bateria'), ('review', 'Revisao'), ('labor', 'Mao de obra'), ('other', 'Outro')], max_length=32)),
                ('part_name', models.CharField(max_length=140)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('part_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_parts', to='garage.motorcycletemplate')),
            ],
            options={
                'ordering': ['part_name', 'manufacturer'],
                'constraints': [models.UniqueConstraint(fields=('template', 'part_name', 'maintenance_type'), name='garage_tpl_part_unique_by_template_name_type')],
            },
        ),
    ]
