# Generated by Django 5.2.13 on 2026-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_motorcycletemplate_motorcycle_source_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcyclespec",
            name="consumption_avg_km_l",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="motorcycletemplatespec",
            name="consumption_avg_km_l",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
