# Generated by Django 5.2.13 on 2026-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
        ('reminders', '0002_alter_reminder_options_remove_reminder_due_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_active'], name='reminder_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['motorcycle', 'is_active'], name='reminder_moto_active_idx'),
        ),
    ]
