# Generated by Django 5.2.13 on 2026-05-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0011_seed_motorcycle_templates"),
        ("reminders", "0003_reminder_reminder_active_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["motorcycle", "is_active", "reference_date"], name="reminder_moto_active_date_idx"
            ),
        ),
    ]
