# Generated by Django 5.2.13 on 2026-06-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0012_part_stock_fields"),
        ("reminders", "0005_push_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reminder",
            name="linked_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_reminders",
                to="maintenance.maintenanceplanitem",
            ),
        ),
    ]
