# Generated by Django 5.2.13 on 2026-04-23 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pushsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.URLField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="pushsubscription",
            constraint=models.UniqueConstraint(fields=("owner", "endpoint"), name="core_push_owner_endpoint_uniq"),
        ),
    ]
