# Generated by Django 6.0.4 on 2026-04-24 03:03

from django.db import migrations


def _delete_attachment_files(apps, schema_editor):
    RecordAttachment = apps.get_model("core", "RecordAttachment")
    for attachment in RecordAttachment.objects.all():
        file_field = attachment.file
        file_name = file_field.name if file_field else ""
        if file_name:
            file_field.storage.delete(file_name)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_pushsubscription_endpoint_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recordattachment",
            name="attach_owner_obj_idx",
        ),
        migrations.RunPython(_delete_attachment_files, _noop),
        migrations.DeleteModel(
            name="RecordAttachment",
        ),
    ]
