# Generated by Django 5.2.13 on 2026-05-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_apitoken_key_hash_pushsubscription_encrypt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(default="Moto Track", max_length=200)),
                ("cnpj", models.CharField(blank=True, default="", max_length=20, verbose_name="CNPJ")),
                ("support_email", models.EmailField(default="suporte@moto-track.net", max_length=254)),
                ("support_phone", models.CharField(blank=True, default="", max_length=30)),
                ("support_whatsapp", models.CharField(blank=True, default="", max_length=30)),
                ("address_street", models.CharField(blank=True, default="", max_length=300)),
                ("address_city", models.CharField(blank=True, default="", max_length=100)),
                ("address_state", models.CharField(blank=True, default="", max_length=2)),
                ("address_zip", models.CharField(blank=True, default="", max_length=10, verbose_name="CEP")),
                (
                    "dpo_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Encarregado de Dados (DPO)"),
                ),
                ("dpo_email", models.EmailField(blank=True, default="", max_length=254, verbose_name="E-mail do DPO")),
                ("terms_last_updated", models.DateField(blank=True, null=True, verbose_name="Termos atualizados em")),
                (
                    "privacy_last_updated",
                    models.DateField(blank=True, null=True, verbose_name="Privacidade atualizada em"),
                ),
                ("lgpd_last_updated", models.DateField(blank=True, null=True, verbose_name="LGPD atualizada em")),
                (
                    "cancellation_last_updated",
                    models.DateField(blank=True, null=True, verbose_name="Cancelamento atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configurações do Site",
                "verbose_name_plural": "Configurações do Site",
            },
        ),
    ]
