# Generated by Django 5.2.13 on 2026-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycledocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
