# Generated by Django 5.2.13 on 2026-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_motorcycledocument_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycledocument',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
