# Generated by Django 5.2.13 on 2026-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_motorcycledocument_valid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycledocument",
            name="notify_before_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
