# Generated by Django 5.2.13 on 2026-04-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tirerecord',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TireProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('tire_type', models.CharField(choices=[('street', 'Street'), ('sport', 'Sport'), ('touring', 'Touring'), ('off_road', 'Off-road'), ('scooter', 'Scooter'), ('other', 'Outro')], default='street', max_length=24)),
                ('width_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rim_diameter_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('load_index', models.CharField(blank=True, max_length=12)),
                ('speed_rating', models.CharField(blank=True, max_length=8)),
                ('max_speed_kmh', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.AddField(
            model_name='tirerecord',
            name='tire_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='tires.tireproduct'),
        ),
    ]
