# Generated by Django 5.2.13 on 2026-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_tirerecord_purchase_price_tireproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
