# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tires", "0003_tirerecord_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tireproduct",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tires/products/"),
        ),
    ]

