# Generated by Django 5.2.13 on 2026-04-14 19:00

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0004_tireproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireproduct',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tirerecord',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='tirerecord',
            name='purchase_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tireproduct',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tirerecord',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tirerecord',
            name='purchase_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
