# Generated by Django 5.2.13 on 2026-04-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_motorcycle_current_odometer_km_and_more'),
        ('tires', '0005_tireproduct_price_currency_tirerecord_cost_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TirePressureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('psi_front', models.PositiveSmallIntegerField()),
                ('psi_rear', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_pressure_records', to='garage.motorcycle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
