# Generated by Django 5.2.13 on 2026-04-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
        ('tires', '0006_tirepressurerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireproduct',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tirerecord',
            index=models.Index(fields=['is_active'], name='tire_record_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tirerecord',
            index=models.Index(fields=['installed_at'], name='tire_record_installed_idx'),
        ),
    ]
