# Generated by Django 5.2.13 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
        ('tires', '0007_alter_tireproduct_owner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tirerecord',
            index=models.Index(fields=['motorcycle', 'installed_at', 'installed_odometer_km'], name='tire_moto_date_odo_idx'),
        ),
    ]
