# Generated by Django 5.2.13 on 2026-04-22 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nome da Peça/Item")),
                ("description", models.TextField(blank=True, verbose_name="Descrição/Anotações")),
                ("part_number", models.CharField(blank=True, max_length=100, verbose_name="Número da Peça (PN)")),
                ("quantity", models.PositiveIntegerField(default=0, verbose_name="Quantidade em Estoque")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10, verbose_name="Custo Unitário Médio"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Inventário",
                "verbose_name_plural": "Itens de Inventário",
                "ordering": ["name"],
            },
        ),
    ]
