# Generated by Django 5.2.13 on 2026-04-22 22:52

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Brazilian Real")], default="BRL", editable=False, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit_cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=djmoney.money.Money(0, "BRL"),
                max_digits=10,
                verbose_name="Custo Unitário Médio",
            ),
        ),
    ]
