# Generated by Django 5.2.13 on 2026-04-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("oil_change", "Troca de oleo"),
                            ("oil_filter", "Filtro de oleo"),
                            ("air_filter", "Filtro de ar"),
                            ("chain_set", "Relacao"),
                            ("brake_pad", "Pastilha de freio"),
                            ("spark_plug", "Vela"),
                            ("battery", "Bateria"),
                            ("review", "Revisao"),
                            ("labor", "Mao de obra"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("date", models.DateField()),
                ("odometer_km", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("parts_used", models.TextField(blank=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("workshop", models.CharField(blank=True, max_length=120)),
                ("next_change_km", models.PositiveIntegerField(blank=True, null=True)),
                ("next_change_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="garage.motorcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-odometer_km"],
            },
        ),
    ]
