# Generated by Django 5.2.13 on 2026-04-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_maintenancerecord_next_change_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('part_type', models.CharField(choices=[('oil', 'Óleo'), ('filter', 'Filtro'), ('chain', 'Corrente/Transmissão'), ('spark_plug', 'Vela'), ('battery', 'Bateria'), ('brake_pad', 'Pastilha'), ('tire', 'Pneu'), ('labor', 'Mão de obra'), ('other', 'Outro')], default='other', max_length=24)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecordPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerecord')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancepart')),
            ],
            options={
                'ordering': ['part__name'],
                'unique_together': {('maintenance_record', 'part')},
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='maintenance_records', through='maintenance.MaintenanceRecordPart', to='maintenance.maintenancepart'),
        ),
    ]
