# Generated by Django 5.2.13 on 2026-04-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_motorcycle_current_odometer_km_and_more'),
        ('maintenance', '0004_maintenancepart_price_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Troca de oleo'), ('oil_filter', 'Filtro de oleo'), ('air_filter', 'Filtro de ar'), ('chain_set', 'Relacao'), ('brake_pad', 'Pastilha de freio'), ('spark_plug', 'Vela'), ('battery', 'Bateria'), ('review', 'Revisao'), ('labor', 'Mao de obra'), ('other', 'Outro')], default='other', max_length=32)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_km', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plan_items', to='garage.motorcycle')),
            ],
            options={
                'ordering': ['maintenance_type', '-is_active', '-updated_at'],
                'unique_together': {('motorcycle', 'maintenance_type')},
            },
        ),
    ]
