# Generated by Django 5.2.13 on 2026-04-17 11:27

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
        ('maintenance', '0005_maintenanceplanitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'BRL'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['date'], name='maint_record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['maintenance_type'], name='maint_record_type_idx'),
        ),
    ]
