# Generated by Django 5.2.13 on 2026-04-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0006_alter_maintenancepart_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceplanitem",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("oil_change", "Troca de óleo"),
                    ("oil_filter", "Filtro de óleo"),
                    ("air_filter", "Filtro de ar"),
                    ("chain_set", "Relação"),
                    ("brake_pad", "Pastilha de freio"),
                    ("spark_plug", "Vela"),
                    ("battery", "Bateria"),
                    ("review", "Revisão"),
                    ("labor", "Mão de obra"),
                    ("other", "Outro"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerecord",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("oil_change", "Troca de óleo"),
                    ("oil_filter", "Filtro de óleo"),
                    ("air_filter", "Filtro de ar"),
                    ("chain_set", "Relação"),
                    ("brake_pad", "Pastilha de freio"),
                    ("spark_plug", "Vela"),
                    ("battery", "Bateria"),
                    ("review", "Revisão"),
                    ("labor", "Mão de obra"),
                    ("other", "Outro"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
