# Generated by Django 5.2.13 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_motorcycle_owner'),
        ('maintenance', '0007_alter_maintenanceplanitem_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['motorcycle', 'date', 'odometer_km'], name='maint_moto_date_odo_idx'),
        ),
    ]
