# Generated by Django 5.2.13 on 2026-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_motorcycletemplate_motorcycle_source_template_and_more'),
        ('maintenance', '0008_maintenancerecord_maint_moto_date_odo_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceplanitem',
            options={'ordering': ['maintenance_type', 'is_severe_duty_override', '-is_active', '-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceplanitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='maintenanceplanitem',
            name='is_severe_duty_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceplanitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceplanitem',
            unique_together={('motorcycle', 'maintenance_type', 'is_severe_duty_override')},
        ),
    ]
