# Generated by Django 5.2.13 on 2026-04-23 04:31

from django.db import migrations, models


def delete_intervalless_plan_items(apps, schema_editor):
    MaintenancePlanItem = apps.get_model("maintenance", "MaintenancePlanItem")
    MaintenancePlanItem.objects.filter(interval_km__isnull=True, interval_days__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0010_motorcyclespec_consumption_avg_km_l_and_more"),
        ("maintenance", "0009_alter_maintenanceplanitem_options_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_intervalless_plan_items, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="maintenanceplanitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_km__isnull", False), ("interval_days__isnull", False), _connector="OR"),
                name="maint_plan_item_has_interval",
            ),
        ),
    ]
