[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db -ra --strict-markers
markers =
    e2e: marks tests as end-to-end / browser tests
    lighthouse: marks tests as Lighthouse performance tests
    slow: marks tests as slow
    smoke: marks tests as smoke tests
