export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      legacy_id_map: {
        Row: {
          source_table: string;
          source_id: string;
          target_id: string;
          created_at: string;
        };
        Insert: {
          source_table: string;
          source_id: string;
          target_id: string;
          created_at?: string;
        };
        Update: {
          source_table?: string;
          source_id?: string;
          target_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          theme: string;
          is_staff: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name?: string | null;
          theme?: string;
          is_staff?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          theme?: string;
          is_staff?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          id: number;
          company_name: string;
          cnpj: string;
          support_email: string;
          support_phone: string;
          support_whatsapp: string;
          address_street: string;
          address_city: string;
          address_state: string;
          address_zip: string;
          dpo_name: string;
          dpo_email: string;
          terms_last_updated: string | null;
          privacy_last_updated: string | null;
          lgpd_last_updated: string | null;
          cancellation_last_updated: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          company_name?: string;
          cnpj?: string;
          support_email?: string;
          support_phone?: string;
          support_whatsapp?: string;
          address_street?: string;
          address_city?: string;
          address_state?: string;
          address_zip?: string;
          dpo_name?: string;
          dpo_email?: string;
          terms_last_updated?: string | null;
          privacy_last_updated?: string | null;
          lgpd_last_updated?: string | null;
          cancellation_last_updated?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          company_name?: string;
          cnpj?: string;
          support_email?: string;
          support_phone?: string;
          support_whatsapp?: string;
          address_street?: string;
          address_city?: string;
          address_state?: string;
          address_zip?: string;
          dpo_name?: string;
          dpo_email?: string;
          terms_last_updated?: string | null;
          privacy_last_updated?: string | null;
          lgpd_last_updated?: string | null;
          cancellation_last_updated?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      motorcycle_templates: {
        Row: {
          id: string;
          brand: string;
          model: string;
          year_from: number;
          year_to: number | null;
          variant: string;
          engine_cc: number;
          country_code: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          brand: string;
          model: string;
          year_from: number;
          year_to?: number | null;
          variant?: string;
          engine_cc: number;
          country_code?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          brand?: string;
          model?: string;
          year_from?: number;
          year_to?: number | null;
          variant?: string;
          engine_cc?: number;
          country_code?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      motorcycle_template_specs: {
        Row: {
          id: string;
          template_id: string;
          fuel_tank_capacity_l: number | null;
          fuel_type_recommendation: string;
          fuel_octane_min: number | null;
          oil_capacity_l: number | null;
          tire_size_front: string;
          tire_size_rear: string;
          tire_speed_rating: string;
          battery_spec: string;
          chain_size: string;
          recommended_tire_pressure_front: string;
          recommended_tire_pressure_rear: string;
          oil_type_recommendation: string;
          oil_viscosity_recommendation: string;
          manual_url: string;
          consumption_avg_km_l: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          fuel_tank_capacity_l?: number | null;
          fuel_type_recommendation?: string;
          fuel_octane_min?: number | null;
          oil_capacity_l?: number | null;
          tire_size_front?: string;
          tire_size_rear?: string;
          tire_speed_rating?: string;
          battery_spec?: string;
          chain_size?: string;
          recommended_tire_pressure_front?: string;
          recommended_tire_pressure_rear?: string;
          oil_type_recommendation?: string;
          oil_viscosity_recommendation?: string;
          manual_url?: string;
          consumption_avg_km_l?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          fuel_tank_capacity_l?: number | null;
          fuel_type_recommendation?: string;
          fuel_octane_min?: number | null;
          oil_capacity_l?: number | null;
          tire_size_front?: string;
          tire_size_rear?: string;
          tire_speed_rating?: string;
          battery_spec?: string;
          chain_size?: string;
          recommended_tire_pressure_front?: string;
          recommended_tire_pressure_rear?: string;
          oil_type_recommendation?: string;
          oil_viscosity_recommendation?: string;
          manual_url?: string;
          consumption_avg_km_l?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      motorcycles: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          brand: string;
          model: string;
          year: number;
          source_template_id: string | null;
          photo_key: string | null;
          license_plate: string;
          is_active: boolean;
          deleted_at: string | null;
          odometer_override_km: number | null;
          odometer_override_at: string | null;
          current_odometer_km: number;
          current_odometer_updated_at: string | null;
          previous_owners: number | null;
          riding_profile: string;
          purchase_price_cents: number | null;
          purchase_currency: string;
          purchase_date: string | null;
          observations: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          brand: string;
          model: string;
          year: number;
          source_template_id?: string | null;
          photo_key?: string | null;
          license_plate?: string;
          is_active?: boolean;
          deleted_at?: string | null;
          odometer_override_km?: number | null;
          odometer_override_at?: string | null;
          current_odometer_km?: number;
          current_odometer_updated_at?: string | null;
          previous_owners?: number | null;
          riding_profile?: string;
          purchase_price_cents?: number | null;
          purchase_currency?: string;
          purchase_date?: string | null;
          observations?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          brand?: string;
          model?: string;
          year?: number;
          source_template_id?: string | null;
          photo_key?: string | null;
          license_plate?: string;
          is_active?: boolean;
          deleted_at?: string | null;
          odometer_override_km?: number | null;
          odometer_override_at?: string | null;
          current_odometer_km?: number;
          current_odometer_updated_at?: string | null;
          previous_owners?: number | null;
          riding_profile?: string;
          purchase_price_cents?: number | null;
          purchase_currency?: string;
          purchase_date?: string | null;
          observations?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      motorcycle_specs: {
        Row: {
          id: string;
          motorcycle_id: string;
          fuel_tank_capacity_l: number | null;
          fuel_type_recommendation: string;
          fuel_octane_min: number | null;
          oil_capacity_l: number | null;
          tire_size_front: string;
          tire_size_rear: string;
          tire_speed_rating: string;
          battery_spec: string;
          chain_size: string;
          recommended_tire_pressure_front: string;
          recommended_tire_pressure_rear: string;
          oil_type_recommendation: string;
          oil_viscosity_recommendation: string;
          manual_reference: string;
          consumption_avg_km_l: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          motorcycle_id: string;
          fuel_tank_capacity_l?: number | null;
          fuel_type_recommendation?: string;
          fuel_octane_min?: number | null;
          oil_capacity_l?: number | null;
          tire_size_front?: string;
          tire_size_rear?: string;
          tire_speed_rating?: string;
          battery_spec?: string;
          chain_size?: string;
          recommended_tire_pressure_front?: string;
          recommended_tire_pressure_rear?: string;
          oil_type_recommendation?: string;
          oil_viscosity_recommendation?: string;
          manual_reference?: string;
          consumption_avg_km_l?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          motorcycle_id?: string;
          fuel_tank_capacity_l?: number | null;
          fuel_type_recommendation?: string;
          fuel_octane_min?: number | null;
          oil_capacity_l?: number | null;
          tire_size_front?: string;
          tire_size_rear?: string;
          tire_speed_rating?: string;
          battery_spec?: string;
          chain_size?: string;
          recommended_tire_pressure_front?: string;
          recommended_tire_pressure_rear?: string;
          oil_type_recommendation?: string;
          oil_viscosity_recommendation?: string;
          manual_reference?: string;
          consumption_avg_km_l?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fuel_stations: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          brand: string;
          city: string;
          state: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          brand?: string;
          city?: string;
          state?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          brand?: string;
          city?: string;
          state?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fuel_grades: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          fuel_type: string;
          octane_rating: number | null;
          ethanol_percentage: number | null;
          default_price_per_liter_millicents: number | null;
          currency: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          fuel_type?: string;
          octane_rating?: number | null;
          ethanol_percentage?: number | null;
          default_price_per_liter_millicents?: number | null;
          currency?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          fuel_type?: string;
          octane_rating?: number | null;
          ethanol_percentage?: number | null;
          default_price_per_liter_millicents?: number | null;
          currency?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fuel_records: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          station_id: string | null;
          fuel_grade_id: string | null;
          date: string;
          odometer_km: number;
          liters: number;
          total_price_cents: number;
          price_per_liter_millicents: number;
          currency: string;
          fuel_type: string;
          tank_full: boolean;
          receipt_file_key: string | null;
          station_name: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          station_id?: string | null;
          fuel_grade_id?: string | null;
          date: string;
          odometer_km: number;
          liters: number;
          total_price_cents?: number;
          price_per_liter_millicents?: number;
          currency?: string;
          fuel_type?: string;
          tank_full?: boolean;
          receipt_file_key?: string | null;
          station_name?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          station_id?: string | null;
          fuel_grade_id?: string | null;
          date?: string;
          odometer_km?: number;
          liters?: number;
          total_price_cents?: number;
          price_per_liter_millicents?: number;
          currency?: string;
          fuel_type?: string;
          tank_full?: boolean;
          receipt_file_key?: string | null;
          station_name?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fuel_preferences: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          station_id: string | null;
          fuel_grade_id: string | null;
          fuel_type: string;
          station_name: string;
          price_per_liter_millicents: number | null;
          currency: string;
          tank_full: boolean;
          use_count: number;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          station_id?: string | null;
          fuel_grade_id?: string | null;
          fuel_type?: string;
          station_name?: string;
          price_per_liter_millicents?: number | null;
          currency?: string;
          tank_full?: boolean;
          use_count?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          station_id?: string | null;
          fuel_grade_id?: string | null;
          fuel_type?: string;
          station_name?: string;
          price_per_liter_millicents?: number | null;
          currency?: string;
          tank_full?: boolean;
          use_count?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fuel_review_preferences: {
        Row: {
          id: string;
          motorcycle_id: string;
          owner_id: string;
          fillups_interval: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          motorcycle_id: string;
          owner_id: string;
          fillups_interval?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          motorcycle_id?: string;
          owner_id?: string;
          fillups_interval?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_parts: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          manufacturer: string;
          part_type: string;
          sku: string;
          price_cents: number | null;
          currency: string;
          track_stock: boolean;
          stock_quantity: number;
          low_stock_threshold: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          manufacturer?: string;
          part_type?: string;
          sku?: string;
          price_cents?: number | null;
          currency?: string;
          track_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          manufacturer?: string;
          part_type?: string;
          sku?: string;
          price_cents?: number | null;
          currency?: string;
          track_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_records: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          maintenance_type: string;
          date: string;
          odometer_km: number;
          description: string;
          parts_used: string;
          cost_cents: number;
          currency: string;
          workshop: string;
          interval_km: number | null;
          interval_days: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          maintenance_type?: string;
          date: string;
          odometer_km: number;
          description?: string;
          parts_used?: string;
          cost_cents?: number;
          currency?: string;
          workshop?: string;
          interval_km?: number | null;
          interval_days?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          maintenance_type?: string;
          date?: string;
          odometer_km?: number;
          description?: string;
          parts_used?: string;
          cost_cents?: number;
          currency?: string;
          workshop?: string;
          interval_km?: number | null;
          interval_days?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_record_parts: {
        Row: {
          id: string;
          owner_id: string;
          maintenance_record_id: string;
          part_id: string;
          quantity: number;
          unit_price_cents: number | null;
          currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          maintenance_record_id: string;
          part_id: string;
          quantity?: number;
          unit_price_cents?: number | null;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          maintenance_record_id?: string;
          part_id?: string;
          quantity?: number;
          unit_price_cents?: number | null;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_plan_items: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string;
          maintenance_type: string;
          interval_km: number | null;
          interval_days: number | null;
          last_done_km: number | null;
          last_done_date: string | null;
          is_severe_duty_override: boolean;
          notes: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id: string;
          maintenance_type?: string;
          interval_km?: number | null;
          interval_days?: number | null;
          last_done_km?: number | null;
          last_done_date?: string | null;
          is_severe_duty_override?: boolean;
          notes?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string;
          maintenance_type?: string;
          interval_km?: number | null;
          interval_days?: number | null;
          last_done_km?: number | null;
          last_done_date?: string | null;
          is_severe_duty_override?: boolean;
          notes?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      maintenance_photos: {
        Row: {
          id: string;
          owner_id: string;
          maintenance_record_id: string;
          image_key: string;
          caption: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          maintenance_record_id: string;
          image_key: string;
          caption?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          maintenance_record_id?: string;
          image_key?: string;
          caption?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tire_products: {
        Row: {
          id: string;
          owner_id: string;
          manufacturer: string;
          model_name: string;
          image_key: string | null;
          tire_type: string;
          width_mm: number | null;
          aspect_ratio: number | null;
          rim_diameter_in: number | null;
          load_index: string;
          speed_rating: string;
          max_speed_kmh: number | null;
          price_cents: number | null;
          currency: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          manufacturer: string;
          model_name: string;
          image_key?: string | null;
          tire_type?: string;
          width_mm?: number | null;
          aspect_ratio?: number | null;
          rim_diameter_in?: number | null;
          load_index?: string;
          speed_rating?: string;
          max_speed_kmh?: number | null;
          price_cents?: number | null;
          currency?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          manufacturer?: string;
          model_name?: string;
          image_key?: string | null;
          tire_type?: string;
          width_mm?: number | null;
          aspect_ratio?: number | null;
          rim_diameter_in?: number | null;
          load_index?: string;
          speed_rating?: string;
          max_speed_kmh?: number | null;
          price_cents?: number | null;
          currency?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tire_records: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          tire_product_id: string | null;
          position: string;
          brand_model: string;
          installed_at: string;
          installed_odometer_km: number;
          cost_cents: number;
          purchase_price_cents: number | null;
          currency: string;
          recommended_pressure: string;
          wear_percent: number;
          estimated_change_km: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          tire_product_id?: string | null;
          position: string;
          brand_model: string;
          installed_at: string;
          installed_odometer_km: number;
          cost_cents?: number;
          purchase_price_cents?: number | null;
          currency?: string;
          recommended_pressure?: string;
          wear_percent?: number;
          estimated_change_km?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          tire_product_id?: string | null;
          position?: string;
          brand_model?: string;
          installed_at?: string;
          installed_odometer_km?: number;
          cost_cents?: number;
          purchase_price_cents?: number | null;
          currency?: string;
          recommended_pressure?: string;
          wear_percent?: number;
          estimated_change_km?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tire_pressure_records: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          date: string;
          psi_front: number;
          psi_rear: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          date: string;
          psi_front: number;
          psi_rear: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          date?: string;
          psi_front?: number;
          psi_rear?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      motorcycle_documents: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          name: string;
          document_type: string;
          file_key: string | null;
          valid_until: string | null;
          notify_before_days: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          name: string;
          document_type?: string;
          file_key?: string | null;
          valid_until?: string | null;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          name?: string;
          document_type?: string;
          file_key?: string | null;
          valid_until?: string | null;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reminders: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          title: string;
          description: string;
          trigger_type: Database["public"]["Enums"]["reminder_trigger_type"];
          trigger_value_km: number | null;
          trigger_value_days: number | null;
          reference_km: number | null;
          reference_date: string | null;
          is_active: boolean;
          last_notified_at: string | null;
          last_email_notified_at: string | null;
          last_push_notified_at: string | null;
          send_email: boolean;
          send_push: boolean;
          notes: string;
          is_recurring: boolean;
          linked_plan_item_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          title: string;
          description?: string;
          trigger_type?: Database["public"]["Enums"]["reminder_trigger_type"];
          trigger_value_km?: number | null;
          trigger_value_days?: number | null;
          reference_km?: number | null;
          reference_date?: string | null;
          is_active?: boolean;
          last_notified_at?: string | null;
          last_email_notified_at?: string | null;
          last_push_notified_at?: string | null;
          send_email?: boolean;
          send_push?: boolean;
          notes?: string;
          is_recurring?: boolean;
          linked_plan_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          title?: string;
          description?: string;
          trigger_type?: Database["public"]["Enums"]["reminder_trigger_type"];
          trigger_value_km?: number | null;
          trigger_value_days?: number | null;
          reference_km?: number | null;
          reference_date?: string | null;
          is_active?: boolean;
          last_notified_at?: string | null;
          last_email_notified_at?: string | null;
          last_push_notified_at?: string | null;
          send_email?: boolean;
          send_push?: boolean;
          notes?: string;
          is_recurring?: boolean;
          linked_plan_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      annual_fees: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          fee_type: string;
          year: number;
          due_date: string;
          paid_date: string | null;
          amount_cents: number;
          currency: string;
          notify_before_days: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          fee_type?: string;
          year: number;
          due_date: string;
          paid_date?: string | null;
          amount_cents?: number;
          currency?: string;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          fee_type?: string;
          year?: number;
          due_date?: string;
          paid_date?: string | null;
          amount_cents?: number;
          currency?: string;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      insurance_policies: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          provider: string;
          policy_number: string;
          coverage_start: string;
          coverage_end: string;
          premium_cents: number;
          currency: string;
          notify_before_days: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          provider: string;
          policy_number?: string;
          coverage_start: string;
          coverage_end: string;
          premium_cents?: number;
          currency?: string;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          provider?: string;
          policy_number?: string;
          coverage_start?: string;
          coverage_end?: string;
          premium_cents?: number;
          currency?: string;
          notify_before_days?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      insurance_claims: {
        Row: {
          id: string;
          owner_id: string;
          policy_id: string | null;
          claim_date: string;
          description: string;
          amount_cents: number | null;
          currency: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          policy_id?: string | null;
          claim_date: string;
          description: string;
          amount_cents?: number | null;
          currency?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          policy_id?: string | null;
          claim_date?: string;
          description?: string;
          amount_cents?: number | null;
          currency?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      professional_cost_settings: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string;
          maintenance_reserve_per_km_millicents: number;
          depreciation_per_km_millicents: number;
          fixed_daily_cost_cents: number;
          currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id: string;
          maintenance_reserve_per_km_millicents?: number;
          depreciation_per_km_millicents?: number;
          fixed_daily_cost_cents?: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string;
          maintenance_reserve_per_km_millicents?: number;
          depreciation_per_km_millicents?: number;
          fixed_daily_cost_cents?: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      work_sessions: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string | null;
          work_date: string;
          started_at: string | null;
          ended_at: string | null;
          odometer_start_km: number;
          odometer_end_km: number;
          gross_income_cents: number;
          tips_cents: number;
          fuel_spent_cents: number | null;
          currency: string;
          deliveries_count: number;
          platform_source: string;
          payment_method: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id?: string | null;
          work_date: string;
          started_at?: string | null;
          ended_at?: string | null;
          odometer_start_km: number;
          odometer_end_km: number;
          gross_income_cents?: number;
          tips_cents?: number;
          fuel_spent_cents?: number | null;
          currency?: string;
          deliveries_count?: number;
          platform_source?: string;
          payment_method?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string | null;
          work_date?: string;
          started_at?: string | null;
          ended_at?: string | null;
          odometer_start_km?: number;
          odometer_end_km?: number;
          gross_income_cents?: number;
          tips_cents?: number;
          fuel_spent_cents?: number | null;
          currency?: string;
          deliveries_count?: number;
          platform_source?: string;
          payment_method?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_profiles: {
        Row: {
          id: string;
          owner_id: string;
          plan: Database["public"]["Enums"]["billing_plan"];
          billing_interval:
            Database["public"]["Enums"]["billing_interval"] | null;
          stripe_customer_id: string;
          stripe_subscription_id: string;
          stripe_subscription_status: string;
          stripe_price_id: string;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          grace_until: string | null;
          latest_invoice_url: string;
          latest_receipt_url: string;
          trial_will_end_notified_at: string | null;
          next_invoice_at: string | null;
          next_invoice_amount_cents: number | null;
          next_invoice_currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          plan?: Database["public"]["Enums"]["billing_plan"];
          billing_interval?:
            Database["public"]["Enums"]["billing_interval"] | null;
          stripe_customer_id?: string;
          stripe_subscription_id?: string;
          stripe_subscription_status?: string;
          stripe_price_id?: string;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          grace_until?: string | null;
          latest_invoice_url?: string;
          latest_receipt_url?: string;
          trial_will_end_notified_at?: string | null;
          next_invoice_at?: string | null;
          next_invoice_amount_cents?: number | null;
          next_invoice_currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          plan?: Database["public"]["Enums"]["billing_plan"];
          billing_interval?:
            Database["public"]["Enums"]["billing_interval"] | null;
          stripe_customer_id?: string;
          stripe_subscription_id?: string;
          stripe_subscription_status?: string;
          stripe_price_id?: string;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          grace_until?: string | null;
          latest_invoice_url?: string;
          latest_receipt_url?: string;
          trial_will_end_notified_at?: string | null;
          next_invoice_at?: string | null;
          next_invoice_amount_cents?: number | null;
          next_invoice_currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      billing_events: {
        Row: {
          id: string;
          stripe_event_id: string;
          event_type: string;
          payload: Json;
          processed_at: string | null;
          processing_error: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          stripe_event_id: string;
          event_type: string;
          payload?: Json;
          processed_at?: string | null;
          processing_error?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          stripe_event_id?: string;
          event_type?: string;
          payload?: Json;
          processed_at?: string | null;
          processing_error?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      account_data_requests: {
        Row: {
          id: string;
          owner_id: string;
          request_type: string;
          status: string;
          notes: string;
          fulfilled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          request_type: string;
          status?: string;
          notes?: string;
          fulfilled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          request_type?: string;
          status?: string;
          notes?: string;
          fulfilled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sale_report_shares: {
        Row: {
          id: string;
          owner_id: string;
          motorcycle_id: string;
          token_prefix: string;
          token_hash: string;
          expires_at: string;
          revoked_at: string | null;
          access_count: number;
          last_accessed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          motorcycle_id: string;
          token_prefix: string;
          token_hash: string;
          expires_at: string;
          revoked_at?: string | null;
          access_count?: number;
          last_accessed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          motorcycle_id?: string;
          token_prefix?: string;
          token_hash?: string;
          expires_at?: string;
          revoked_at?: string | null;
          access_count?: number;
          last_accessed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      forum_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
        };
        Relationships: [];
      };
      forum_articles: {
        Row: {
          id: string;
          title: string;
          slug: string;
          summary: string;
          meta_description: string;
          cover_image_key: string | null;
          body: string;
          is_published: boolean;
          published_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          summary: string;
          meta_description?: string;
          cover_image_key?: string | null;
          body: string;
          is_published?: boolean;
          published_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          meta_description?: string;
          cover_image_key?: string | null;
          body?: string;
          is_published?: boolean;
          published_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      forum_article_categories: {
        Row: {
          article_id: string | null;
          category_id: string | null;
        };
        Insert: {
          article_id?: string | null;
          category_id?: string | null;
        };
        Update: {
          article_id?: string | null;
          category_id?: string | null;
        };
        Relationships: [];
      };
      article_comments: {
        Row: {
          id: string;
          owner_id: string;
          article_id: string | null;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          article_id?: string | null;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          article_id?: string | null;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      article_reactions: {
        Row: {
          id: string;
          owner_id: string;
          article_id: string | null;
          emoji: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          article_id?: string | null;
          emoji: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          article_id?: string | null;
          emoji?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      api_tokens: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          scopes: string;
          is_active: boolean;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          key_hash: string;
          key_prefix?: string;
          scopes?: string;
          is_active?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          key_hash?: string;
          key_prefix?: string;
          scopes?: string;
          is_active?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          owner_id: string;
          endpoint_encrypted: string;
          endpoint_hash: string;
          p256dh_encrypted: string;
          auth_encrypted: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          endpoint_encrypted: string;
          endpoint_hash: string;
          p256dh_encrypted: string;
          auth_encrypted: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          endpoint_encrypted?: string;
          endpoint_hash?: string;
          p256dh_encrypted?: string;
          auth_encrypted?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_submissions: {
        Row: {
          id: string;
          owner_id: string;
          token: string;
          action: string;
          result_model: string;
          result_pk: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          token: string;
          action: string;
          result_model?: string;
          result_pk?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          token?: string;
          action?: string;
          result_model?: string;
          result_pk?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      object_files: {
        Row: {
          id: string;
          owner_id: string;
          module: string;
          source_table: string;
          source_id: string | null;
          object_key: string;
          filename: string;
          content_type: string;
          byte_size: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          module: string;
          source_table: string;
          source_id?: string | null;
          object_key: string;
          filename: string;
          content_type?: string;
          byte_size?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          module?: string;
          source_table?: string;
          source_id?: string | null;
          object_key?: string;
          filename?: string;
          content_type?: string;
          byte_size?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      billing_plan: "free" | "pro";
      billing_interval: "monthly" | "yearly";
      reminder_trigger_type: "by_km" | "by_date" | "by_interval";
      severity_level: "critical" | "warning" | "success" | "info";
    };
    CompositeTypes: Record<string, never>;
  };
};

export type PublicTableName = keyof Database["public"]["Tables"];
