# Generated by Django 5.2.13 on 2026-04-15 11:28

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0006_motorcycle_current_odometer_km_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=120)),
                ("policy_number", models.CharField(blank=True, max_length=80)),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                (
                    "premium_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Brazilian Real")], default="BRL", editable=False, max_length=3
                    ),
                ),
                ("premium", djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ("notify_before_days", models.PositiveSmallIntegerField(default=30)),
                ("notes", models.TextField(blank=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="garage.motorcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["-coverage_end", "provider"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Brazilian Real")], default="BRL", editable=False, max_length=3, null=True
                    ),
                ),
                ("amount", djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberto"), ("settled", "Resolvido"), ("denied", "Negado")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="expenses.insurancepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-claim_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnualFee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("ipva", "IPVA"),
                            ("dpvat", "DPVAT"),
                            ("licensing", "Licenciamento"),
                            ("other", "Outro"),
                        ],
                        default="ipva",
                        max_length=24,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Brazilian Real")], default="BRL", editable=False, max_length=3
                    ),
                ),
                ("amount", djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ("notify_before_days", models.PositiveSmallIntegerField(default=30)),
                ("notes", models.TextField(blank=True)),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="annual_fees", to="garage.motorcycle"
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
                "unique_together": {("motorcycle", "fee_type", "year")},
            },
        ),
    ]
