# Generated by Django 5.2.13 on 2026-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('garage', '0008_alter_motorcycle_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annualfee',
            index=models.Index(fields=['due_date'], name='annual_fee_due_date_idx'),
        ),
    ]
