# Generated by Django 5.2.13 on 2026-04-23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForumArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.CharField(max_length=280)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("-published_at", "-id")},
        ),
    ]
