# Generated by Django 5.2.13 on 2026-04-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumarticle",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Imagem de capa para Open Graph (recomendado 1200x630).",
                upload_to="blog/covers/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="forumarticle",
            name="meta_description",
            field=models.CharField(
                blank=True, help_text="Descricao para SEO/metas. Deixe em branco para usar o resumo.", max_length=280
            ),
        ),
    ]
