# Generated by Django 5.2.13 on 2026-04-23 22:52

from django.db import migrations
from django.utils import timezone


def seed_articles(apps, schema_editor):
    ForumArticle = apps.get_model("forum", "ForumArticle")
    articles = [
        {
            "title": "Como calcular o consumo exato de combustivel da Honda CB 500X",
            "slug": "como-calcular-consumo-combustivel-honda-cb-500x",
            "summary": "Aprenda a medir o consumo real da sua CB 500X usando o metodo do tanque cheio, com planilha gratuita e comparativo entre versões.",
            "meta_description": "Guia passo a passo para calcular o consumo exato da Honda CB 500X. Metodo do tanque cheio, planilha gratuita e dicas de economia.",
            "body": (
                "## Por que o painel mente?\n\n"
                "O computador de bordo da CB 500X calcula a media instantanea, mas ignora variaveis como vento, carga e altitude. "
                "Para saber o consumo **real**, use o metodo do tanque cheio.\n\n"
                "## Passo a passo\n\n"
                "1. **Encha o tanque** ate a borda, anote o odometro.\n"
                "2. **Rod pelo menos 200 km** no seu ritmo habitual.\n"
                "3. **Retorne ao mesmo posto e bomba**, encha novamente ate a borda.\n"
                "4. **Anote os litros** abastecidos e a quilometragem percorrida.\n"
                "5. **Divida km por litros**: ex. 215 km / 8,4 L = **25,6 km/L**.\n\n"
                "## Valores de referencia\n\n"
                "| Versao | Cidade | Estrada |\n"
                "|--------|--------|---------|\n"
                "| CB 500X 2019-2021 | 22-25 km/L | 28-31 km/L |\n"
                "| CB 500X 2022+ (Euro 5) | 24-27 km/L | 30-33 km/L |\n\n"
                "## Dicas para economizar\n\n"
                "- Mantenha a pressao dos pneus em 29 psi (dianteiro) e 33 psi (traseiro).\n"
                "- Use marchas curtas apenas para ultrapassar; cruzeiro em 6ª a 5.000 rpm e o ponto ideal.\n"
                "- Evite malas laterais cheias em viagens longas; elas aumentam a resistencia aerodinamica.\n\n"
                "> **Dica do Moto Track:** cadastre cada abastecimento no app e acompanhe a curva de consumo automaticamente."
            ),
        },
        {
            "title": "Cronograma de manutencao da corrente Yamaha: MT-07, XJ6 e Tracer 900",
            "slug": "cronograma-manutencao-corrente-yamaha-mt07-xj6-tracer900",
            "summary": "Descubra quando lubrificar, ajustar e trocar a corrente da sua Yamaha. Tabela com intervalos por modelo e sinais de desgaste.",
            "meta_description": "Guia completo de manutencao da corrente para Yamaha MT-07, XJ6 e Tracer 900. Intervalos, lubrificacao, ajuste e troca.",
            "body": (
                "## A corrente e o coracao da transmissao\n\n"
                "Em motos com pinhao e coroa, a corrente transmite 100% da potencia do motor para a roda. "
                "Negligenciar ela e o mesmo que jogar dinheiro no lixo — e arriscar uma quebra em alta velocidade.\n\n"
                "## Intervalos por modelo\n\n"
                "| Modelo | Lubrificacao | Ajuste de folga | Troca da corrente |\n"
                "|--------|--------------|-----------------|-------------------|\n"
                "| MT-07 (2014-2024) | A cada 1.000 km | A cada 5.000 km | 25.000-30.000 km |\n"
                "| XJ6 (2009-2020) | A cada 1.000 km | A cada 5.000 km | 20.000-25.000 km |\n"
                "| Tracer 900 / GT (2015+) | A cada 1.000 km | A cada 5.000 km | 25.000-30.000 km |\n\n"
                "## Como medir a folga correta\n\n"
                "1. Coloque a moto na bengala central.\n"
                "2. Encontre o ponto medio entre o pinhao e a coroa.\n"
                "3. Empurre a corrente para baixo e meca a folga.\n"
                "4. Para a maioria das Yamaha, a folga ideal fica entre **30 e 40 mm**.\n\n"
                "## Sinais de que e hora de trocar\n\n"
                "- **Engripamento**: a corrente nao dobra suavemente ao aperta-la.\n"
                "- **Desgaste nos roletes**: aparecem dentes pontiagudos nos elos.\n"
                "- **Ajuste maximo**: as marcas de ajuste do balancim chegaram ao limite.\n\n"
                "> **Lembrete do Moto Track:** configure um lembrete de lubrificacao a cada 1.000 km direto no app."
            ),
        },
        {
            "title": "Guia completo: troca de oleo da Yamaha FZ25 e Fazer 250",
            "slug": "guia-troca-oleo-yamaha-fz25-fazer-250",
            "summary": "Tudo sobre a troca de oleo da Fazer 250: tipo ideal, quantidade, torque do filtro, ferramentas necessarias e passo a passo com fotos.",
            "meta_description": "Passo a passo completo para trocar o oleo da Yamaha FZ25 e Fazer 250. Especificacoes, torque, filtros e ferramentas.",
            "body": (
                "## Especificacoes oficiais\n\n"
                "| Item | Especificacao |\n"
                "|------|---------------|\n"
                "| Oleio recomendado | Yamalube 20W-40 semissintetico ou equivalente API SN |\n"
                "| Capacidade total | **1,3 litros** (sem filtro) / **1,5 litros** (com filtro) |\n"
                "| Filtro de oleo | Yamaha original 5D3-E3440-00 ou compativel Bosch/Mann |\n"
                "| Torque do tampao de drenagem | **20 Nm** (nao aperte demais!) |\n"
                "| Torque do filtro | **10 Nm** ou aperto manual + 3/4 de volta |\n\n"
                "## Passo a passo\n\n"
                "1. **Aqueca o motor** por 3 minutos para o oleo escoar melhor.\n"
                "2. **Retire a vareta** e o tampao de enchimento para ventilar.\n"
                "3. **Coloque a bandeja** e solte o parafuso de drenagem (17 mm).\n"
                "4. **Retire o filtro velho** com a chave de gancho ou a pinca.\n"
                "5. **Lubrifique a borracha** do novo filtro com oleo novo antes de instalar.\n"
                "6. **Feche a drenagem** com torque de 20 Nm e nova arruela de aluminio.\n"
                "7. **Encha com 1,3 L**, ligue por 30 segundos, desligue e aguarde 2 minutos.\n"
                "8. **Complete ate a marca maxima** da vareta (geralmente +200 mL).\n\n"
                "## Cuidados comuns\n\n"
                "- Nao reutilize a arruela de drenagem de aluminio; ela deforma e vaza.\n"
                "- Nunca use oleo de carro; a FZ25 precisa de aditivos para embreagem em banho de oleio.\n"
                "- Troque a cada **5.000 km** com oleo semissintetico ou **3.000 km** com mineral.\n\n"
                "> **No Moto Track:** registre a troca e receba um lembrete automatico antes dos 5.000 km."
            ),
        },
        {
            "title": "Quando trocar as pastilhas de freio da Honda CB 300F Twister?",
            "slug": "quando-trocar-pastilhas-freio-honda-cb-300f-twister",
            "summary": "Saiba identificar o momento certo de trocar as pastilhas da Twister. Medicao da lona, codigos das pecas e comparativo entre dianteiro e traseiro.",
            "meta_description": "Guia visual para saber quando trocar as pastilhas de freio da Honda CB 300F Twister. Medicao, codigos e procedimento.",
            "body": (
                "## O limite minimo da lona\n\n"
                "A Honda recomenda trocar as pastilhas quando a lona de atrito atingir **1,0 mm de espessura restante**. "
                "Abaixo disso, o suporte metalico pode riscar o disco e comprometer a frenagem em emergencias.\n\n"
                "## Medicao em casa (sem desmontar tudo)\n\n"
                "1. **Olhe pela fresta** do caliper com uma lanterna; se a lona estiver proxima do nivel do suporte, e hora.\n"
                "2. **Remova a pinça dianteira** (2 parafusos de 12 mm) e meca com uma regua ou paquimetro.\n"
                "3. **Traseiro:** o cilindro mestre empurra menos fluido; o desgaste e mais lento, mas verifique a cada 10.000 km.\n\n"
                "## Codigos das pecas originais\n\n"
                "| Posicao | Codigo Honda | Codigo Bosch |\n"
                "|---------|--------------|--------------|\n"
                "| Dianteira | 06455-KVK-901 | BB 8326 |\n"
                "| Traseira | 06455-KTE-901 | BB 8327 |\n\n"
                "## Quanto duram na pratica?\n\n"
                "- **Dianteira:** 15.000-25.000 km (uso urbano agressivo chega a 12.000 km).\n"
                "- **Traseira:** 25.000-35.000 km (uso moderado).\n\n"
                "**Atenção:** se voce sentir vibracao ou apito ao frear, a lona pode estar esfarelada ou o disco pode estar empenado.\n\n"
                "> **Dica Moto Track:** anote a data e KM da troca no app e receba alerta antes do proximo desgaste."
            ),
        },
        {
            "title": "Checklist de seguranca para viajar de moto no Brasil",
            "slug": "checklist-seguranca-viajar-moto-brasil",
            "summary": "Nao saia de casa sem conferir estes 15 itens. Checklist completo para viagens de moto no Brasil: documentos, equipamentos, pneus e mecanica.",
            "meta_description": "Checklist essencial de seguranca para viagens de moto no Brasil. Documentos, equipamentos, revisao mecanica e primeiros socorros.",
            "body": (
                "## Antes de ligar o motor\n\n"
                "### Documentos e papelada\n"
                "- [ ] CNH com permissao para categoria da moto\n"
                "- [ ] CRLV (licenciamento) atualizado no celular ou impresso\n"
                "- [ ] Seguro vigente com numero da corretora salvo\n"
                "- [ ] Carteira de vacinacao (se for para areas rurais)\n\n"
                "### Equipamento pessoal\n"
                "- [ ] Capacete com viseira limpa e mecanismo de trava funcionando\n"
                "- [ ] Jaqueta com protecao de ombros, cotovelos e costas\n"
                "- [ ] Luvas de couro ou texxtile com protecao de junlga\n"
                "- [ ] Bota que cubra o tornozelo (minimo)\n"
                "- [ ] Calca jeans reforcada ou de cordura; bermuda e proibida\n\n"
                "### Mecanica basica\n"
                "- [ ] Pressao dos pneus frios (confira na manual)\n"
                "- [ ] Nivel de oleo entre as marcas da vareta\n"
                "- [ ] Fluido de freio transparente/ambardo (se estiver preto, troque)\n"
                "- [ ] Luzes altas, baixas, freio e setas funcionando\n"
                "- [ ] Corrente lubrificada e com folga correta\n"
                "- [ ] Kit de reparo de pneu (macarrão + CO2 ou compressor)\n\n"
                "## Na estrada\n\n"
                "- Pare a cada 150-200 km para hidratar e descansar.\n"
                "- Nunca ultrapasse de lado direito; use a faixa da esquerda apenas para ultrapassar.\n"
                "- Mantenha distancia de 2 segundos do veiculo da frente.\n"
                "- Em rodovias de pista simples, carros costumam te enxergar tarde; use farol alto de dia.\n\n"
                "> **Moto Track em viagem:** registre cada abastecimento para saber onde foi mais caro e planejar o retorno."
            ),
        },
        {
            "title": "Como ajustar a suspensao traseira da sua moto para diferentes cargas",
            "slug": "como-ajustar-suspensao-traseira-cargas-diferentes",
            "summary": "Aprenda a regular a pre-carga da mola traseira para pilotar sozinho, com garupa ou carregado. Guia universal para monoshock e twin-shock.",
            "meta_description": "Guia pratico para ajustar a pre-carga da suspensao traseira conforme a carga. Monoshock, twin-shock e recomendacoes por cenario.",
            "body": (
                "## Por que a pre-carga importa?\n\n"
                "A pre-carga da mola traseira define quanto a suspensao **afunda** com o peso da moto, piloto, garupa e bagagem. "
                "Sem ajuste correto, voce perde estabilidade em curvas, conforto em buracos e aderencia na frenagem.\n\n"
                "## Tipos de ajuste\n\n"
                "| Sistema | Como ajustar | Ferramenta |\n"
                "|---------|--------------|------------|\n"
                "| Monoshock com rosca | Gire a rosca superior da mola | Gancho ou chave de suspensao |\n"
                "| Monoshock com ferramenta | Use a chave de garra incluida no kit | Chave de suspensao 68-72 mm |\n"
                "| Twin-shock (2 amortecedores) | Ajuste ambos igualmente via rosca ou click | Chave de fenda grande |\n\n"
                "## Recomendacoes de ajuste\n\n"
                "- **Piloto sozinho (até 80 kg):** pre-carga minima ou 1 click acima do minimo.\n"
                "- **Piloto + garupa:** adicione 2-3 clicks ou 1/4 de volta na rosca.\n"
                "- **Piloto + alforge/bau:** adicione 3-4 clicks; se ainda afundar muito, considere uma mola mais dura.\n"
                "- **Viagem com carga maxima:** use o ajuste maximo de pre-carga, mas nao ultrapasse o curso total do amortecedor.\n\n"
                "## Teste pratico\n\n"
                "1. Ajuste a suspensao para a carga esperada.\n"
                "2. Empurre o banco para baixo com as maos e solte; a moto deve oscilar 1-2 vezes e parar.\n"
                "3. Sente-se na moto e peça para alguem observar: o braco oscilante deve descer cerca de **25-30 mm** (medida sag).\n\n"
                "> **Controle tudo no Moto Track:** registre os ajustes de suspensao como observacao da moto e compare o consumo antes/depois."
            ),
        },
    ]
    for article_data in articles:
        ForumArticle.objects.get_or_create(slug=article_data["slug"], defaults={
            **article_data,
            "is_published": True,
            "published_at": timezone.now(),
        })


def reverse_seed(apps, schema_editor):
    ForumArticle = apps.get_model("forum", "ForumArticle")
    slugs = [
        "como-calcular-consumo-combustivel-honda-cb-500x",
        "cronograma-manutencao-corrente-yamaha-mt07-xj6-tracer900",
        "guia-troca-oleo-yamaha-fz25-fazer-250",
        "quando-trocar-pastilhas-freio-honda-cb-300f-twister",
        "checklist-seguranca-viajar-moto-brasil",
        "como-ajustar-suspensao-traseira-cargas-diferentes",
    ]
    ForumArticle.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_forumarticle_cover_image_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_articles, reverse_seed),
    ]
