# Generated by Django 5.2.13 on 2026-04-23 23:26

from django.db import migrations


def enhance_articles(apps, schema_editor):
    ForumArticle = apps.get_model("forum", "ForumArticle")

    updates = [
        {
            "slug": "como-calcular-consumo-combustivel-honda-cb-500x",
            "summary": "Metodo do tanque cheio para medir o consumo real da Honda CB 500X. Tabela comparativa por versao, 7 fatores que alteram o gasto e planilha para acompanhamento a longo prazo.",
            "meta_description": "Guia completo para calcular o consumo exato da Honda CB 500X. Metodo do tanque cheio, valores de referencia por versao e anos, fatores que influenciam e planilha.",
            "body": (
                "## Por que o painel da CB 500X nao mostra o consumo real?\n\n"
                "O computador de bordo da CB 500X calcula uma media instantanea baseada no fluxo dos injetores e no tempo decorrido. "
                "Na pratica, ele nao considera vento contra, carga na moto, altitude, qualidade do combustivel e temperatura ambiente. "
                "Diferencas de 5% a 12% entre o painel e a realidade sao comuns. Para saber quanto sua moto bebe de verdade, existe um unico metodo confiavel: **o tanque cheio**.\n\n"
                "## O metodo do tanque cheio (passo a passo)\n\n"
                "Este metodo e usado ate por fabricantes em testes homologados. Siga rigorosamente:\n\n"
                "1. **Encha o tanque ate a borda** do bocal, sem espuma. Anote a quilometragem exata do odometro.\n"
                "2. **Percorra no minimo 200 km** no seu ritmo habitual (nao acelere mais nem menos do que o normal).\n"
                "3. **Retorne ao MESMO posto e a MESMA bomba** para minimizar erro de calibracao do bico.\n"
                "4. **Encha novamente ate a borda**, na mesma posicao da moto (vertical, na central).\n"
                "5. **Anote os litros abastecidos** com precisao de uma casa decimal.\n"
                "6. **Calcule**: km percorridos / litros abastecidos = consumo em km/L.\n\n"
                "> **Exemplo:** Se voce rodou 248 km e abasteceu 9,8 litros, o consumo foi 248 / 9,8 = **25,31 km/L**.\n\n"
                "## Valores de referencia reais da CB 500X\n\n"
                "| Versao | Cidade | Estrada 80 km/h | Estrada 120 km/h |\n"
                "|--------|--------|-----------------|-------------------|\n"
                "| 2013-2015 | 20-23 km/L | 26-29 km/L | 22-25 km/L |\n"
                "| 2016-2018 | 21-24 km/L | 27-30 km/L | 23-26 km/L |\n"
                "| 2019-2021 | 22-25 km/L | 28-31 km/L | 24-27 km/L |\n"
                "| 2022+ (Euro 5) | 24-27 km/L | 30-33 km/L | 25-28 km/L |\n\n"
                "*Dados de relatos de proprietarios e testes independentes.*\n\n"
                "## 7 fatores que aumentam (ou reduzem) o consumo\n\n"
                "1. **Pressao dos pneus:** Abaixo de 29 psi (dianteiro) e 33 psi (traseiro) aumenta resistencia ao rolamento e rouba ate 1,5 km/L.\n"
                "2. **Velocidade de cruzeiro:** A 120 km/h o consumo cai 15-20% em relacao a 90 km/h pela resistencia aerodinamica.\n"
                "3. **Carga e aerodinamica:** Malas laterais cheias aumentam arrasto. Um top case alto piora ainda mais.\n"
                "4. **Altitude:** Acima de 1.000 m a mistura pode ficar pobre e consumir mais.\n"
                "5. **Combustivel:** Gasolina adulterada ou com etanol em excesso reduz rendimento.\n"
                "6. **Filtro de ar entupido:** Pode reduzir o consumo em ate 2 km/L porque a injecao compensa.\n"
                "7. **Estilo de pilotagem:** Reduzir marchas em subidas muito antes do necessario faz o motor girar em alta sem necessidade.\n\n"
                "## Erros comuns na medicao\n\n"
                "- **Nao usar a mesma bomba:** Cada bico tem tolerancia de calibracao. Trocar de posto introduz erro.\n"
                "- **Calcular com poucos quilometros:** Rodar apenas 50 km amplifica erros de arredondamento. Minimo: 200 km.\n"
                "- **Nivelar a moto diferente:** Inclinar para o lado do bocal enche menos combustivel e distorce o resultado.\n"
                "- **Esquecer odometro parcial:** O trip da CB 500X reseta ao desligar a ignicao apos algum tempo. Use o odometro total.\n\n"
                "## Acompanhe no Moto Track\n\n"
                "Em vez de anotar no papel, cadastre cada abastecimento no Moto Track. O app calcula automaticamente consumo medio por tanque, "
                "tendencia mensal, custo por km e alerta quando o consumo cair muito — sinal de filtro de ar sujo, pneu murcho ou injecao com problema."
            ),
        },
        {
            "slug": "cronograma-manutencao-corrente-yamaha-mt07-xj6-tracer900",
            "summary": "Cronograma completo de manutencao da corrente para Yamaha MT-07, XJ6 e Tracer 900. Tipos de lubrificante, medicao de folga correta, sinais de corrente esticada e quando trocar coroa e pinhao.",
            "meta_description": "Cronograma completo de manutencao da corrente Yamaha MT-07, XJ6 e Tracer 900. Lubrificacao, ajuste de folga, sinais de desgaste e troca de coroa e pinhao.",
            "body": (
                "## Por que a corrente e o item mais negligenciado da moto?\n\n"
                "Muitos pilotos trocam oleo e filtro religiosamente, mas esquecem a corrente. Resultado: pinhao com dentes em gancho, coroa com desgaste lateral acentuado, "
                "e no pior caso, corrente arrebentando em alta velocidade e travando a roda traseira. A boa noticia: manter uma corrente exige apenas 15 minutos a cada 500 km.\n\n"
                "## Cronograma de manutencao da corrente\n\n"
                "| Intervalo | Tarefa | Tempo estimado |\n"
                "|-----------|--------|----------------|\n"
                "| A cada 500 km | Lubrificar com corrente limpa e seca | 10 minutos |\n"
                "| A cada 1.000 km | Verificar folga e ajustar se necessario | 15 minutos |\n"
                "| A cada 3.000 km | Limpar com kerosene e escova, relubrificar | 30 minutos |\n"
                "| A cada 15.000-20.000 km | Avaliar troca da corrente e coroa/pinhao | Inspecao em oficina |\n\n"
                "## Como medir a folga corretamente\n\n\n"
                "1. Coloque a moto no cavalete central (se tiver) ou peça ajuda para levantar a traseira.\n"
                "2. Encontre o ponto medio da corrente entre a coroa e o pinhao.\n"
                "3. Com um dedo, empurre a corrente para baixo ate o limite.\n"
                "4. Solte e meca a distancia entre o ponto mais alto e o mais baixo.\n"
                "5. **Valor ideal para Yamaha MT-07, XJ6 e Tracer 900: 25 a 35 mm.**\n\n"
                "Se estiver abaixo de 20 mm, a corrente esta muito tensionada e forca os rolamentos do pinhao. "
                "Se estiver acima de 40 mm, a corrente bate no protetor e desgasta o kit de transmissao aceleradamente.\n\n"
                "## Tipos de lubrificante e quando usar cada um\n\n"
                "- **Parafina em spray (base cera):** Ideal para uso urbano e estrada de asfalto. Nao suja a roda traseira e resiste a agua moderada.\n"
                "- **Graxa branca (lithium):** Melhor para chuva constante e estrada de terra. Dura mais, mas suja a roda. Limpe semanalmente.\n"
                "- **Oleo de corrente sintetico:** Para motos de alta cilindrada com alta potencia (Tracer 900). Reduz atrito e aquecimento.\n"
                "- **Ode graxa industrial:** NUNCA. E atrativa e atrai areia como ima, funcionando como lixa na corrente.\n\n"
                "## Sinais de que a corrente precisa ser trocada\n\n"
                "- **Folga maxima ajustada, mas ainda solta:** A corrente ja esticou além do limite de ajuste do tensionador.\n"
                "- **Engates rigidos:** Se algum link da corrente nao flexiona suavemente, ha oxidação interna nos retentores.\n"
                "- **Ruido metalico constante:** Corrente batendo na coroa com folga excessiva.\n"
                "- **O-ring visivelmente danificado:** Borrachas dos retentores de graxa estao ressecadas ou quebradas.\n"
                "- **Dentes do pinhao em formato de gancho:** O pinhao ja desgastou e vai destruir a nova corrente em poucos mil quilometros.\n\n"
                "## Dica profissional: troque tudo junto\n\n"
                "Nunca troque apenas a corrente sem avaliar a coroa e o pinhao. Um pinhao gasto destroi uma corrente nova em 3.000 km. "
                "Um kit completo (corrente + coroa + pinhao) para a MT-07 custa entre R$ 350 e R$ 600 dependendo da marca. "
                "A economia de trocar apenas a corrente e ilusoria — voce gastara o dobro em curto prazo.\n\n"
                "## Ferramentas necessarias para o ajuste em casa\n\n"
                "- Chave de fenda grande (para tensionar a roda)\n"
                "- Chave Allen 6 mm ou 12 mm (depende do modelo)\n"
                "- Torquimetro (para apertar o eixo traseiro: 80-100 Nm na maioria das Yamahas)\n"
                "- Cavalete traseiro (altamente recomendado, mas nao obrigatorio)\n"
                "- Regua ou fita metrica\n\n"
                "Se nao se sentir confortavel com o torque do eixo traseiro, leve a moto a uma oficina para o ajuste de folga. "
                "A lubrificacao em casa, porem, e simples e deve ser feita semanalmente."
            ),
        },
        {
            "slug": "guia-troca-oleo-yamaha-fz25-fazer-250",
            "summary": "Tudo sobre a troca de oleo da Yamaha Fazer 250: tipo ideal (mineral vs sintetico), viscosidade recomendada, quantidade exata, torque do filtro e passo a passo completo.",
            "meta_description": "Passo a passo completo para trocar o oleo da Yamaha FZ25 e Fazer 250. Especificacoes de viscosidade, torque, filtros recomendados e ferramentas.",
            "body": (
                "## Por que a troca de oleo e a manutencao mais importante da moto\n\n"
                "O oleo do motor e o sangue da moto. Ele lubrifica os cilindros, refrigera o cabecote, limpa impurezas e mantem a vedacao dos aneis. "
                "Na Yamaha FZ25/Fazer 250, a recomendacao de fabrica e a cada 5.000 km ou 6 meses. Na pratica, "
                "quem roda muito em cidade com muitas paradas deve considerar trocar a cada 4.000 km.\n\n"
                "## Especificacoes do oleo para FZ25/Fazer 250\n\n"
                "A Yamaha recomenda SAE 10W-30 ou 10W-40 semissintetico (API SL ou superior) para a maioria dos cenarios brasileiros.\n\n"
                "- **Clima quente (acima de 35C):** 15W-40 ou 20W-50 para manter a pelicula lubrificante em alta temperatura.\n"
                "- **Clima frio (abaixo de 10C):** 5W-30 para facilitar a partida a frio e reduzir desgaste inicial.\n"
                "- **Uso intenso/estradas longas:** 10W-40 sintetico (API SN) para maior estabilidade termica.\n\n"
                "## Quantidade, filtro e torque\n\n"
                "| Item | Especificacao |\n"
                "|------|---------------|\n"
                "| Capacidade total (com filtro) | 1,30 litros |\n"
                "| Capacidade sem filtro | 1,15 litros |\n"
                "| Filtro recomendado | Yamaha original (5D7-E3440-00) ou Fram CH-6009 |\n"
                "| Torque bujao drenagem | 20 Nm |\n"
                "| Torque filtro oleo | 10 Nm (nao aperte demais!) |\n"
                "| Intervalo recomendado | 5.000 km / 6 meses |\n\n"
                "## Passo a passo da troca\n\n"
                "1. **Aqueca o motor** por 3-5 minutos: o oleo quente drena melhor e leva mais impurezas.\n"
                "2. **Retire a tampa do enchimento** (na parte superior direita do motor) para despressurizar.\n"
                "3. **Coloque o recipiente** embaixo da moto.\n"
                "4. **Solte o bujao de drenagem** com chave 17 mm no sentido anti-horario.\n"
                "5. **Aguarde 5-10 minutos** ate parar de pingar.\n"
                "6. **Remova o filtro antigo** com chave de filtro ou cinta.\n"
                "7. **Passe oleo novo no anel de borracha** do filtro novo antes de instalar.\n"
                "8. **Instale o filtro novo** e aperte com a mao ate encostar, depois mais 3/4 de volta.\n"
                "9. **Feche o bujao** com torque de 20 Nm.\n"
                "10. **Encha com 1,15 litros** inicialmente.\n"
                "11. **Ligue a moto por 30 segundos** e desligue.\n"
                "12. **Aguarde 2 minutos** e verifique o nivel na vareta. Complete se necessario.\n\n"
                "## Primeira troca (quebra de motor)\n\n"
                "A primeira troca deve ocorrer aos 1.000 km. Use oleo mineral barato nesta fase — ele ajuda a "
                "assentar os aneis e remove particulas de fabricacao. Troque tambem o filtro nesta primeira vez. "
                "Apos a quebra, migre para semissintetico ou sintetico.\n\n"
                "## Erros comuns que destroem o motor\n\n"
                "- **Nunca usar oleo de carro:** Motos precisam de aditivos para embreagem molhada. Oleo de carro pode fazer a embreagem patinar.\n"
                "- **Nao trocar o filtro:** O filtro retem particulas metalicas. Trocar oleo sem trocar filtro e como tomar banho de roupa suja.\n"
                "- **Aperto excessivo no bujao:** Pode danificar as roscas do carter. Use sempre torque correto.\n"
                "- **Nivel errado:** Oleo acima do maximo causa pressao excessiva e vazamentos pelos retentores. Abaixo do minimo causa desgaste acelerado.\n\n"
                "## Descarte correto do oleo usado\n\n"
                "Armazene em garrafa PET limpa e entregue em postos de combustivel ou oficinas autorizadas. "
                "O oleo usado e altamente toxico e poluente. Nunca descarte no ralo ou lixo comum."
            ),
        },
        {
            "slug": "quando-trocar-pastilhas-freio-honda-cb-300f-twister",
            "summary": "Saiba identificar o momento certo de trocar as pastilhas da Twister. Sintomas de desgaste, tipos de material, codigos das pecas e procedimento completo.",
            "meta_description": "Guia visual para saber quando trocar as pastilhas de freio da Honda CB 300F Twister. Sintomas, tipos de material, codigos das pecas e procedimento.",
            "body": (
                "## Como identificar pastilhas de freio gastas na CB 300F Twister\n\n"
                "A pastilha de freio tem uma camada de atrito sobre uma base metalica. Quando essa camada se esgota, "
                "o metal da base comeca a arranhar o disco. Isso causa ruido, vibracao e danos permanentes ao disco de freio. "
                "A regra de ouro: troque ANTES de ouvir o ranger.\n\n"
                "## Medicao da lona de freio\n\n"
                "1. **Olhe pela janela do disco:** A pastilha e visivel sem desmontar nada.\n"
                "2. **Meca a espessura da camada de atrito:** Se estiver abaixo de 2 mm, e hora de trocar.\n"
                "3. **Verifique o indicador de desgaste:** Se a ranhura desapareceu, a pastilha esta no limite.\n"
                "4. **Teste de pedalada:** Se o pedal de freio traseiro ou a manete dianteira viajam muito antes de travar, "
                "pode ser desgaste ou ar no sistema.\n\n"
                "## Tipos de pastilha e quando usar cada uma\n\n"
                "| Tipo | Caracteristica | Melhor para | Preco medio (par) |\n"
                "|------|----------------|-------------|-------------------|\n"
                "| Organica (resina) | Aquece pouco, baixo desgaste do disco | Uso urbano, iniciantes | R$ 40-70 |\n"
                "| Sinterizada (metal) | Alta performance, resiste ao calor | Estrada, pilotos agressivos | R$ 80-130 |\n"
                "| Ceramica | Baixo po, silenciosa, dura mais | Uso misto | R$ 90-150 |\n\n"
                "Para a Twister em uso urbano, pastilha organica ou ceramica e suficiente. Sinterizada so faz sentido "
                "se voce roda muito em descidas longas ou pista.\n\n"
                "## Codigos das pecas e compatibilidade\n\n"
                "- **Dianteiro original Honda:** 06455-KVK-900\n"
                "- **Traseiro original Honda:** 06430-KTE-901\n"
                "- **Compativel dianteiro:** Cobreq N-907, TKS Yamaha Crosser (mesma pinça)\n"
                "- **Compativel traseiro:** Freio a tambor — a pastilha e de lona (sapata), codigo 43120-KTE-900\n\n"
                "Nota: A Twister 2022+ usa pinça dianteira diferente. Verifique o ano antes de comprar.\n\n"
                "## Procedimento de troca das pastilhas dianteiras\n\n"
                "1. Afrouxe os parafusos do eixo da roda.\n"
                "2. Levante a moto com cavalete central ou macaco.\n"
                "3. Retire o eixo da roda e tire a roda dianteira.\n"
                "4. Afrouxe os dois parafusos da pinça (chave Allen 5 mm).\n"
                "5. Retire o pino de travamento das pastilhas e puxe as velhas.\n"
                "6. **Empurre o pistao para dentro** com uma chave de fenda limpa.\n"
                "7. Instale as novas pastilhas no sentido correto (a seta aponta para a frente da moto).\n"
                "8. Lubrifique o pino guia com graxa de silicone.\n"
                "9. Monte a pinça, a roda e aperte o eixo com torque correto (65 Nm).\n\n"
                "## Acasamento (bedding-in) das novas pastilhas\n\n\n"
                "Novas pastilhas precisam de acasamento para transferir uma fina camada de material para o disco. "
                "Sem isso, o freio sera fraco nos primeiros 200 km. Procedimento:\n\n"
                "1. Acelere ate 60 km/h.\n"
                "2. Freie moderadamente ate 20 km/h.\n"
                "3. Acelere novamente sem parar completamente.\n"
                "4. Repita 10 vezes.\n"
                "5. Deixe esfriar por 10 minutos sem usar o freio.\n"
                "6. Evite freadas bruscas nos primeiros 100 km.\n\n"
                "## Quando trocar tambem o disco?\n\n"
                "Se o disco apresentar:\n"
                "- **Ondulacao:** A moto treme ao frear. Diferenca maior que 0,3 mm entre pontos opostos = troca.\n"
                "- **Ranhuras profundas:** Se o dedo encaixar na ranhura, e hora de trocar.\n"
                "- **Espessura minima:** Disco dianteiro da Twister deve ter no minimo 3,5 mm.\n"
                "- **Fissuras:** Qualquer trinca no disco exige troca imediata.\n\n"
                "Disco dianteiro original Honda custa entre R$ 280 e R$ 450. Discos aftermarket de boa qualidade custam R$ 150-250."
            ),
        },
        {
            "slug": "checklist-seguranca-viajar-moto-brasil",
            "summary": "Checklist completo com 20 itens essenciais para viajar de moto no Brasil. Documentos, equipamentos, revisao mecanica e dicas de seguranca para cada regiao.",
            "meta_description": "Checklist essencial de seguranca para viagens de moto no Brasil. Documentos, equipamentos, revisao mecanica e consideracoes regionais.",
            "body": (
                "## Por que um checklist pode salvar sua viagem (e sua vida)\n\n"
                "O Brasil tem mais de 1,7 milhao de km de rodovias, passando por biomas completamente diferentes. "
                "Uma moto que funciona em Sao Paulo pode apresentar problemas no cerrado ou na serra gaucha. "
                "Este checklist cobre documentos, mecanica, equipamentos e consideracoes regionais.\n\n"
                "## 1. Documentos e burocracia\n\n"
                "- [ ] CRLV (licenciamento atualizado) — impresso ou digital via app do Detran\n"
                "- [ ] CNH dentro da validade (verifique categoria A)\n"
                "- [ ] Seguro da moto com cobertura para roubo e acidente em outro estado\n"
                "- [ ] DPVAT pago (obrigatorio ate a compensacao do seguro obrigatorio)\n\n"
                "## 2. Mecanica basica (verificar 1 semana antes)\n\n"
                "- [ ] Oleo do motor dentro do nivel e dentro do prazo de troca\n"
                "- [ ] Pneus com sulco minimo de 2 mm e pressao calibrada (verifique com carga de viagem)\n"
                "- [ ] Pastilhas de freio com mais de 3 mm de material\n"
                "- [ ] Corrente lubrificada e com folga correta (se aplicavel)\n"
                "- [ ] Fluido de freio dentro do nivel e sem cor marrom (fluido novo e amarelo-claro)\n"
                "- [ ] Luminarias, setas e lanterna funcionando\n\n"
                "## 3. Equipamentos obrigatorios e recomendados\n\n"
                "- [ ] Capacete com viseira limpa e bem ajustada (selo INMETRO)\n"
                "- [ ] Luvas de couro com protecao de nós dos dedos\n"
                "- [ ] Jaqueta com protetores de ombros, cotovelos e costas\n"
                "- [ ] Calca de couro ou cordura com protecao de joelhos\n"
                "- [ ] Bota que cubra o tornozelo (minimo: cano medio)\n\n"
                "## 4. Kit de emergencia e ferramentas\n\n"
                "- [ ] Kit de reparo de pneu (macarrão + alicate + bomba de mao ou CO2)\n"
                "- [ ] Chaves Allen, Phillips e fenda (ajuste para sua moto especifica)\n"
                "- [ ] Cabo de acelerador reserva (compativel com seu modelo)\n"
                "- [ ] Fusivel reserva (se sua moto usa fusivel)\n"
                "- [ ] Lanterna de cabeça ou de mao\n"
                "- [ ] Fita isolante e abraçadeiras de nylon\n\n"
                "## 5. Consideracoes regionais do Brasil\n\n"
                "- **Norte (Amazonia):** Chuva intensa e imprevisivel entre outubro e maio. Leve capa de chuva impermeavel e protetor de corrente extra.\n"
                "- **Nordeste (sertao):** Temperaturas acima de 40C. Use oleo mais viscoso (15W-40), leve muito agua e protetor solar.\n"
                "- **Centro-Oeste:** Estradas de terra longas e postos espacados. Leve galao reserva de 5 litros.\n"
                "- **Sul (Serra Gaucha):** Temperaturas negativas no inverno. Luvas termicas e jaqueta com forro sao essenciais.\n"
                "- **Sudeste (Estrada Real):** Serra com neblina e curvas acentuadas. Cuidado com folha molhada e caminhao na contramao.\n\n"
                "## 6. Apps e tecnologia\n\n"
                "- **Waze ou Google Maps:** Para evitar congestionamento e encontrar postos. Baixe mapas offline para regioes sem sinal.\n"
                "- **WhatsApp grupos de motociclismo:** Comunidades locais ajudam em emergencias e indicam mecanicos confiáveis.\n"
                "- **Moto Track:** Cadastre revisões, abastecimentos e lembretes para manter a moto sempre pronta para a proxima viagem.\n\n"
                "## Dica final: divida o primeiro dia\n\n"
                "Se voce nao esta acostumado a rodar mais de 300 km por dia, comece com 200 km no primeiro dia. "
                "O cansaço acumula silenciosamente e a fadiga e responsavel por 30% dos acidentes de moto em viagens longas. "
                "Pare a cada 150 km, hidrate-se, estique as pernas e avalie sua condicao antes de continuar."
            ),
        },
        {
            "slug": "como-ajustar-suspensao-traseira-cargas-diferentes",
            "summary": "Guia pratico para regular a pre-carga da suspensao traseira conforme a carga. Monoshock, twin-shock e recomendacoes por cenario com tabela de referencia.",
            "meta_description": "Guia pratico para ajustar a pre-carga da suspensao traseira conforme a carga. Monoshock, twin-shock, sag de corrida e recomendacoes por cenario.",
            "body": (
                "## Por que ajustar a suspensao traseira e tao importante\n\n"
                "A suspensao traseira controla tracao, estabilidade em curvas e conforto. "
                "Com a pre-carga errada, a moto pode patinar na aceleracao, tombar em curvas lentas ou bater no chao em lombadas. "
                "O ajuste leva 2 minutos e transforma completamente o comportamento da moto.\n\n"
                "## Conceitos basicos: pre-carga, compressao e retorno\n\n"
                "- **Pre-carga (preload):** Ajusta a tensao da mola para suportar peso diferente. Afeta altura da moto e curso disponivel.\n"
                "- **Compressao (compression):** Controla a velocidade com que a suspensao comprime. Mais = mais firme, menos = mais macio.\n"
                "- **Retorno (rebound):** Controla a velocidade com que a suspensao volta. Mais = volta devagar, menos = volta rapido.\n\n"
                "## Sag de corrida (race sag) vs sag livre (free sag)\n\n"
                "O sag e a distancia que a suspensao afunda com o peso do piloto.\n\n"
                "| Tipo de moto | Sag de corrida ideal | Sag livre ideal |\n"
                "|--------------|---------------------|-----------------|\n"
                "| Naked/street (MT-03, CB 300F) | 25-30 mm | 5-10 mm |\n"
                "| Trail/adventure (CB 500X, Versys) | 35-40 mm | 10-15 mm |\n"
                "| Esportiva (CBR 600RR, R6) | 30-35 mm | 5-10 mm |\n"
                "| Custom/Cruiser (Shadow, Boulevard) | 30-35 mm | 10-15 mm |\n\n"
                "## Como medir o sag corretamente\n\n"
                "1. **Sag livre:** Levante a roda traseira no cavalete central. Meça do eixo traseiro ate um ponto fixo no chassi (ex: parafuso do banco).\n"
                "2. **Sag de corrida:** Desça a moto, suba sem ajuda de ninguem, nao empurre. Meça do mesmo ponto.\n"
                "3. **Calcule:** Sag de corrida = medida livre - medida com piloto.\n\n"
                "## Ajuste de pre-carga por cenario\n\n"
                "| Cenario | Posicao da mola | Por que |\n"
                "|---------|----------------|---------|\n"
                "| Sozinho, sem bagagem | Posicao mais macia (0-1) | Maximo conforto e curso |\n"
                "| Sozinho, com mochila/malas | Meio (2-3) | Compensa peso extra nas costas |\n"
                "| Com garupa, sem bagagem | Meio-alto (3-4) | Suporta peso extra na traseira |\n"
                "| Com garupa e bagagem | Posicao mais firme (maximo) | Evita bater no fundo em lombadas |\n"
                "| Estrada de terra leve | Um clique mais firme que urbano | Evita bottoming em buracos |\n"
                "| Pista / curvas agressivas | Mais firme (4-5) | Reduz transferencia de peso excessiva |\n\n"
                "## Tipos de ajuste de pre-carga\n\n"
                "- **Anel de rosca (collar):** Gire com chave de fenda ou ferramenta especifica. Sente cada clique.\n"
                "- **Ferramenta de encaixe (C-spanner):** Comum em suspensoes com molas mais duras.\n"
                "- **Hidraulica (eletronica):** Algumas motos premium ajustam via botao no guidao.\n\n"
                "## Quando a suspensao precisa de manutencao (oleo interno)\n\n"
                "A suspensao traseira (monoshock) usa oleo hidraulico que se degrada com o tempo. Sinais de necessidade:\n"
                "- A moto pula em lombadas em vez de absorver\n"
                "- Ha ruido de oleo passando rapido demais (chiado metalico)\n"
                "- O retorno parece instantaneo (rebound muito rapido)\n"
                "- Vazamento de oleo pelo retentor do amortecedor\n\n"
                "A revisao do amortecedor traseiro custa entre R$ 250 e R$ 600 dependendo da moto e da oficina. "
                "Recomendada a cada 20.000-30.000 km para motos de uso intenso."
            ),
        },
    ]

    for data in updates:
        article = ForumArticle.objects.filter(slug=data["slug"]).first()
        if article:
            article.summary = data["summary"]
            article.meta_description = data["meta_description"]
            article.body = data["body"]
            article.save()


def reverse_enhance(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_seed_blog_articles"),
    ]

    operations = [
        migrations.RunPython(enhance_articles, reverse_enhance),
    ]
